export enum QueryKeys {
  UserData = 'UserData',
  Users = 'Users',
  User = 'User',
  UserDataPorfile = 'UserDataPorfile',
  PutUser = 'PutUser',
  Cities = 'Cities',
  Customers = 'Customers',
  Treatments = 'Treatments',
  Equipments = 'Equipments',
  ConsultingsRooms = 'ConsultingsRooms',
  CustomerInfo = 'CustomerInfo',
  Equipment = 'Equipment',
  ConsultingRoom = 'ConsultingRoom',
  Consultations = 'Consultations',
  ConsultingsRoomsHook = 'ConsultingsRoomsHook',
  EquipmentsHook = 'EquipmentsHook',
}
